// frontend/theme/generate-palette.js
//
// Writes theme/palette.css: every Tailwind colour the UI uses, as CSS
// variables. :root keeps Tailwind's own colours (the dark admin panel looks
// exactly as before); [data-theme='light'] remaps them for the cream public
// site: "white" (main text on dark) becomes dark ink, light text shades
// become their dark counterparts so they stay readable on cream, and the
// indigo/sky/violet accents become the green brand.
//
// Run after changing a colour:  node theme/generate-palette.js
const fs = require('fs')
const path = require('path')
const colors = require('tailwindcss/colors')
const { FAMILIES } = require('./families')

const SHADES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]

const rgb = hex => {
  const h = hex.replace('#', '')
  const n = parseInt(h.length === 3 ? h.split('').map(c => c + c).join('') : h, 16)
  return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`
}

// Brand green (headings and buttons of the reference design: #0b6b4b).
const BRAND = {
  50: '#ecf7f1', 100: '#d2eddf', 200: '#a6dac0', 300: '#6fbf98', 400: '#3a9e72',
  500: '#15845a', 600: '#0b6b4b', 700: '#08573d', 800: '#064431', 900: '#053627', 950: '#032219',
}
// Warm greys for body text on cream, light → dark is reversed on purpose:
// slate-300/400 are "body text" in the dark design.
const LIGHT_SLATE = {
  50: '#1c2a22', 100: '#26302a', 200: '#33392f', 300: '#4a4236', 400: '#5e5444', 500: '#7d6f5a',
  600: '#9c8e77', 700: '#c9bca3', 800: '#e6dcc6', 900: '#f3ecdd', 950: '#faf5ea',
}
const INK = '#1c2a22'
const LIGHT_SOURCE = { indigo: BRAND, sky: colors.teal, violet: colors.green }

// Light text shades become dark ones; mid and dark shades stay.
const INVERT = { 50: 950, 100: 900, 200: 800, 300: 700, 400: 600 }

let dark = ':root {\n  --tw-white: 255 255 255;\n'
let light = "[data-theme='light'] {\n" + `  --tw-white: ${rgb(INK)};\n`
for (const family of FAMILIES) {
  for (const shade of SHADES) {
    dark += `  --tw-${family}-${shade}: ${rgb(colors[family][shade])};\n`
    let value
    if (family === 'slate') value = LIGHT_SLATE[shade]
    else {
      const source = LIGHT_SOURCE[family] || colors[family]
      value = source[INVERT[shade] || shade]
    }
    light += `  --tw-${family}-${shade}: ${rgb(value)};\n`
  }
}
dark += '}\n'
light += '}\n'

const out = path.join(__dirname, 'palette.css')
fs.writeFileSync(
  out,
  '/* Generated by theme/generate-palette.js — edit that file, not this one. */\n' + dark + '\n' + light,
)
console.log('wrote', out)
